### PR TITLE
Hide title bar, block moving and resizing of counter windows

### PR DESCRIPTION
**Pull request by raohmaru**
Hi!
I love your addon! But I was missing the functionality to block the window (so it is not moved or resized accidentally).
I have added this new options to the config window, and also another option to hide the title bar.

### CODE REVIEW

**Comment by StephenCWills** [comment]
It looks like there are a few whitespace issues in your commits. If you are using Notepad++, I recommend using the `Edit > Blank Operations > TAB to Space` and `Edit > Blank Operations > Trim Trailing Space` features on the init.lua file to fix the spacing.

On a side note, I wanted to share a really simple script you might find interesting. I use this script to override styles for all my addons. I can also use the `Delete` key to toggle the NoResize and NoMove flags.
https://gist.github.com/StephenCWills/8958dedfb285853fbe654170256106b9

**Comment by StephenCWills** [comment]
FYI, I'm sorry if my feedback and/or inactivity has been a little disheartening. I just haven't had a chance to get a good look at your code. I don't mean to drive you away, I've just been really busy lately. I'll try to give this a proper look next week.

**Comment by raohmaru** [comment]
No worries at all! I just wanted to contribute to your plugin beacuse I find it really useful and I just needed this features.

Trailing whitespaces removed :)

Really interesting the snippet for overriding style settings. Not sure if it will be useful to toggle the  NoResize and NoMove flags with a keystroke, but definetely it is for show/hide the windows.

**Comment by StephenCWills** [comment]
Just got around to merging this in. Again, I have to apologize for how obscenely long this took me. I took a big, long break from addon development and just recently got back into it.

**Pull request merged**
